// questions.js — Question bank for Robo Tug of War
// loadQuestions(n) returns n shuffled questions from a randomly chosen set.
// Each set has 100+ questions. Add more sets freely.

const QUESTION_SETS = [

// ══════════════════════════════════════════════════════
// SET 1 — General Knowledge (106 questions)
// ══════════════════════════════════════════════════════
[
  {q:"What is the capital of France?",options:["Berlin","Madrid","Paris","Rome"],answer:2},
  {q:"How many sides does a hexagon have?",options:["5","6","7","8"],answer:1},
  {q:"What planet is known as the Red Planet?",options:["Venus","Saturn","Jupiter","Mars"],answer:3},
  {q:"Who painted the Mona Lisa?",options:["Michelangelo","Leonardo da Vinci","Raphael","Donatello"],answer:1},
  {q:"What is the chemical symbol for gold?",options:["Gd","Go","Au","Ag"],answer:2},
  {q:"How many continents are on Earth?",options:["5","6","7","8"],answer:2},
  {q:"What is the largest ocean on Earth?",options:["Atlantic","Indian","Arctic","Pacific"],answer:3},
  {q:"In what year did World War II end?",options:["1943","1944","1945","1946"],answer:2},
  {q:"What is the fastest land animal?",options:["Lion","Cheetah","Leopard","Horse"],answer:1},
  {q:"How many bones are in the adult human body?",options:["196","206","216","226"],answer:1},
  {q:"What gas do plants absorb from the air?",options:["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"],answer:2},
  {q:"Which country is home to the kangaroo?",options:["New Zealand","South Africa","Brazil","Australia"],answer:3},
  {q:"What is the square root of 144?",options:["10","11","12","13"],answer:2},
  {q:"What is H2O commonly known as?",options:["Salt","Sugar","Water","Acid"],answer:2},
  {q:"How many strings does a standard guitar have?",options:["4","5","6","7"],answer:2},
  {q:"What is the capital of Japan?",options:["Osaka","Kyoto","Hiroshima","Tokyo"],answer:3},
  {q:"Which country invented pizza?",options:["France","Spain","Greece","Italy"],answer:3},
  {q:"How many hours are in a day?",options:["20","22","24","26"],answer:2},
  {q:"What is the largest planet in our solar system?",options:["Saturn","Uranus","Neptune","Jupiter"],answer:3},
  {q:"Which metal is liquid at room temperature?",options:["Lead","Iron","Mercury","Zinc"],answer:2},
  {q:"How many letters are in the English alphabet?",options:["24","25","26","27"],answer:2},
  {q:"What is the capital of Australia?",options:["Sydney","Melbourne","Brisbane","Canberra"],answer:3},
  {q:"Who wrote Romeo and Juliet?",options:["Charles Dickens","William Shakespeare","Mark Twain","Jane Austen"],answer:1},
  {q:"How many days are in a leap year?",options:["364","365","366","367"],answer:2},
  {q:"What is the smallest prime number?",options:["0","1","2","3"],answer:2},
  {q:"Which ocean is the saltiest?",options:["Pacific","Atlantic","Indian","Arctic"],answer:1},
  {q:"What is the capital of Brazil?",options:["Rio de Janeiro","São Paulo","Salvador","Brasília"],answer:3},
  {q:"How many teeth does an adult human have?",options:["28","30","32","34"],answer:2},
  {q:"What is the chemical symbol for water?",options:["WO","H2O","HO2","W2O"],answer:1},
  {q:"Which country has the largest population?",options:["USA","India","China","Russia"],answer:2},
  {q:"What is the tallest mountain on Earth?",options:["K2","Kangchenjunga","Mount Everest","Lhotse"],answer:2},
  {q:"Who discovered gravity?",options:["Albert Einstein","Isaac Newton","Galileo","Copernicus"],answer:1},
  {q:"What is the currency of Japan?",options:["Won","Yuan","Yen","Ringgit"],answer:2},
  {q:"How many planets are in our solar system?",options:["7","8","9","10"],answer:1},
  {q:"What is the capital of Germany?",options:["Munich","Hamburg","Frankfurt","Berlin"],answer:3},
  {q:"Which is the longest river in the world?",options:["Amazon","Mississippi","Yangtze","Nile"],answer:3},
  {q:"What is the boiling point of water (°C)?",options:["90","95","100","105"],answer:2},
  {q:"What is the hardest natural substance?",options:["Gold","Iron","Diamond","Quartz"],answer:2},
  {q:"What colour is a ruby?",options:["Blue","Green","Red","Yellow"],answer:2},
  {q:"How many sides does a triangle have?",options:["2","3","4","5"],answer:1},
  {q:"What is the capital of Canada?",options:["Toronto","Vancouver","Montreal","Ottawa"],answer:3},
  {q:"Which instrument has black and white keys?",options:["Guitar","Violin","Piano","Flute"],answer:2},
  {q:"What is the national animal of Australia?",options:["Koala","Kangaroo","Emu","Wombat"],answer:1},
  {q:"How many zeros are in one million?",options:["4","5","6","7"],answer:2},
  {q:"Which gas makes up most of Earth's atmosphere?",options:["Oxygen","Carbon Dioxide","Nitrogen","Argon"],answer:2},
  {q:"What is the longest bone in the human body?",options:["Spine","Femur","Tibia","Humerus"],answer:1},
  {q:"In which city is the Eiffel Tower?",options:["Rome","London","Madrid","Paris"],answer:3},
  {q:"What is 15% of 200?",options:["20","25","30","35"],answer:2},
  {q:"Which planet is closest to the Sun?",options:["Venus","Earth","Mars","Mercury"],answer:3},
  {q:"What do bees produce?",options:["Milk","Honey","Wax only","Silk"],answer:1},
  {q:"How many sides does an octagon have?",options:["6","7","8","9"],answer:2},
  {q:"What colour is the sky on a clear day?",options:["White","Grey","Blue","Green"],answer:2},
  {q:"Who was the first US President?",options:["John Adams","Thomas Jefferson","George Washington","James Madison"],answer:2},
  {q:"How many minutes are in an hour?",options:["50","55","60","65"],answer:2},
  {q:"What is the capital of Italy?",options:["Milan","Venice","Florence","Rome"],answer:3},
  {q:"Which fruit is known as the king of fruits?",options:["Mango","Durian","Jackfruit","Pineapple"],answer:1},
  {q:"How many hearts does an octopus have?",options:["1","2","3","4"],answer:2},
  {q:"What is 7 × 8?",options:["54","56","58","60"],answer:1},
  {q:"Which is the smallest continent?",options:["Europe","Antarctica","Australia","South America"],answer:2},
  {q:"What colour are emeralds?",options:["Red","Blue","Green","Purple"],answer:2},
  {q:"Who invented the telephone?",options:["Thomas Edison","Alexander Graham Bell","Nikola Tesla","Guglielmo Marconi"],answer:1},
  {q:"What is the capital of Spain?",options:["Barcelona","Seville","Valencia","Madrid"],answer:3},
  {q:"How many chromosomes do humans have?",options:["23","44","46","48"],answer:2},
  {q:"What is the chemical symbol for iron?",options:["Ir","Fe","In","Fi"],answer:1},
  {q:"Which country is shaped like a boot?",options:["Greece","Spain","Portugal","Italy"],answer:3},
  {q:"What is the largest desert on Earth?",options:["Gobi","Sahara","Arabian","Antarctic"],answer:3},
  {q:"How many days are in February in a non-leap year?",options:["26","27","28","29"],answer:2},
  {q:"What is the speed of light (approx km/s)?",options:["200,000","300,000","400,000","500,000"],answer:1},
  {q:"Which country has the most natural lakes?",options:["USA","Russia","China","Canada"],answer:3},
  {q:"What is 12 squared?",options:["124","134","144","154"],answer:2},
  {q:"Which blood type is the universal donor?",options:["A+","B−","O−","AB+"],answer:2},
  {q:"How many keys does a standard piano have?",options:["76","80","84","88"],answer:3},
  {q:"What is the capital of Russia?",options:["St. Petersburg","Novosibirsk","Kiev","Moscow"],answer:3},
  {q:"Which organ pumps blood around the body?",options:["Lungs","Liver","Kidneys","Heart"],answer:3},
  {q:"What is the freezing point of water (°C)?",options:["-10","−5","0","5"],answer:2},
  {q:"How many seconds are in a minute?",options:["50","55","60","65"],answer:2},
  {q:"What type of animal is a dolphin?",options:["Fish","Reptile","Mammal","Amphibian"],answer:2},
  {q:"What is the capital of Egypt?",options:["Alexandria","Luxor","Giza","Cairo"],answer:3},
  {q:"Which planet has rings around it?",options:["Jupiter","Uranus","Saturn","Neptune"],answer:2},
  {q:"How many sides does a pentagon have?",options:["4","5","6","7"],answer:1},
  {q:"What gas do humans exhale?",options:["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"],answer:2},
  {q:"What is 100 ÷ 4?",options:["20","25","30","35"],answer:1},
  {q:"Which is the smallest country in the world?",options:["Monaco","San Marino","Nauru","Vatican City"],answer:3},
  {q:"What is the national flower of Japan?",options:["Rose","Lotus","Cherry Blossom","Tulip"],answer:2},
  {q:"How many sides does a cube have?",options:["4","5","6","8"],answer:2},
  {q:"What is the capital of Mexico?",options:["Guadalajara","Monterrey","Puebla","Mexico City"],answer:3},
  {q:"Which sense is associated with the nose?",options:["Sight","Hearing","Smell","Touch"],answer:2},
  {q:"What is 9 × 9?",options:["72","81","90","99"],answer:1},
  {q:"What colour are sapphires?",options:["Red","Green","Blue","Yellow"],answer:2},
  {q:"How many seasons are there in a year?",options:["2","3","4","5"],answer:2},
  {q:"What is the capital of South Korea?",options:["Busan","Incheon","Daegu","Seoul"],answer:3},
  {q:"Which is the largest land animal?",options:["Giraffe","Hippopotamus","African Elephant","White Rhinoceros"],answer:2},
  {q:"What is the main ingredient in guacamole?",options:["Tomato","Avocado","Mango","Cucumber"],answer:1},
  {q:"How many strings does a violin have?",options:["3","4","5","6"],answer:1},
  {q:"What is the capital of India?",options:["Mumbai","Kolkata","Chennai","New Delhi"],answer:3},
  {q:"Which planet is known as the Blue Planet?",options:["Neptune","Uranus","Saturn","Earth"],answer:3},
  {q:"What does DNA stand for?",options:["Deoxyribonucleic Acid","Diribonucleic Acid","Dinuclear Acid","Deoxyribose Acid"],answer:0},
  {q:"How many faces does a tetrahedron have?",options:["3","4","5","6"],answer:1},
  {q:"What is the capital of Argentina?",options:["Santiago","Lima","Montevideo","Buenos Aires"],answer:3},
  {q:"Which mammal can fly?",options:["Flying Squirrel","Bat","Flying Fish","Sugar Glider"],answer:1},
],

// ══════════════════════════════════════════════════════
// SET 2 — Science & Technology (105 questions)
// ══════════════════════════════════════════════════════
[
  {q:"What is the powerhouse of the cell?",options:["Nucleus","Ribosome","Mitochondria","Vacuole"],answer:2},
  {q:"What force keeps planets in orbit?",options:["Magnetism","Gravity","Friction","Nuclear force"],answer:1},
  {q:"What is the atomic number of carbon?",options:["4","6","8","12"],answer:1},
  {q:"What is the chemical formula for salt?",options:["KCl","NaCl","MgCl","CaCl"],answer:1},
  {q:"What organ produces insulin?",options:["Liver","Kidney","Pancreas","Spleen"],answer:2},
  {q:"What is the process plants use to make food?",options:["Respiration","Fermentation","Photosynthesis","Osmosis"],answer:2},
  {q:"How many chambers does the human heart have?",options:["2","3","4","5"],answer:2},
  {q:"What particle has a negative charge?",options:["Proton","Neutron","Electron","Positron"],answer:2},
  {q:"What is the unit of electrical resistance?",options:["Volt","Ampere","Watt","Ohm"],answer:3},
  {q:"What is the chemical symbol for oxygen?",options:["O","Ox","Oy","Om"],answer:0},
  {q:"What type of energy does the Sun primarily produce?",options:["Chemical","Kinetic","Nuclear","Magnetic"],answer:2},
  {q:"Which planet has the most moons?",options:["Jupiter","Saturn","Uranus","Neptune"],answer:1},
  {q:"What is the study of fossils called?",options:["Geology","Archaeology","Palaeontology","Biology"],answer:2},
  {q:"What is the pH of pure water?",options:["5","6","7","8"],answer:2},
  {q:"What gas is released during photosynthesis?",options:["Carbon Dioxide","Nitrogen","Oxygen","Hydrogen"],answer:2},
  {q:"Which element has the symbol Na?",options:["Nickel","Sodium","Nitrogen","Neon"],answer:1},
  {q:"What is the unit of force?",options:["Watt","Joule","Newton","Pascal"],answer:2},
  {q:"What is the closest star to Earth?",options:["Sirius","Betelgeuse","Proxima Centauri","The Sun"],answer:3},
  {q:"What does CPU stand for?",options:["Central Processing Unit","Computer Power Unit","Central Power Utility","Control Processing Unit"],answer:0},
  {q:"What is the hardest natural mineral?",options:["Ruby","Diamond","Quartz","Topaz"],answer:1},
  {q:"What is the chemical symbol for silver?",options:["Si","Sv","Ag","Al"],answer:2},
  {q:"What type of wave is sound?",options:["Electromagnetic","Transverse","Longitudinal","Gamma"],answer:2},
  {q:"What is the unit of electric current?",options:["Volt","Ampere","Ohm","Watt"],answer:1},
  {q:"Which is the most abundant element in the universe?",options:["Helium","Oxygen","Carbon","Hydrogen"],answer:3},
  {q:"What does RAM stand for?",options:["Random Access Memory","Read Access Memory","Rapid Access Module","Random Array Memory"],answer:0},
  {q:"What part of the eye controls how much light enters?",options:["Retina","Cornea","Iris","Pupil"],answer:2},
  {q:"What is the formula for speed?",options:["Speed = Distance × Time","Speed = Distance ÷ Time","Speed = Time ÷ Distance","Speed = Force ÷ Mass"],answer:1},
  {q:"What is the study of earthquakes called?",options:["Volcanology","Seismology","Meteorology","Geology"],answer:1},
  {q:"How many bits are in a byte?",options:["4","6","8","16"],answer:2},
  {q:"Which planet rotates on its side?",options:["Neptune","Saturn","Uranus","Mars"],answer:2},
  {q:"What is the symbol for potassium?",options:["P","Po","Pt","K"],answer:3},
  {q:"What is the human body's largest organ?",options:["Liver","Lungs","Brain","Skin"],answer:3},
  {q:"What causes rainbows?",options:["Reflection only","Refraction and dispersion","Diffraction","Absorption"],answer:1},
  {q:"How many protons does hydrogen have?",options:["0","1","2","3"],answer:1},
  {q:"What is the chemical symbol for gold?",options:["Go","Gd","Gl","Au"],answer:3},
  {q:"Which bone protects the brain?",options:["Sternum","Femur","Skull","Vertebra"],answer:2},
  {q:"What is the speed of light (approx)?",options:["200,000 km/s","300,000 km/s","400,000 km/s","500,000 km/s"],answer:1},
  {q:"What kind of animal is a salamander?",options:["Reptile","Mammal","Amphibian","Fish"],answer:2},
  {q:"What is the function of red blood cells?",options:["Fight infection","Carry oxygen","Digest food","Filter blood"],answer:1},
  {q:"What is binary code based on?",options:["Base 8","Base 10","Base 2","Base 16"],answer:2},
  {q:"What is Newton's first law about?",options:["Gravity","Inertia","Action-reaction","Acceleration"],answer:1},
  {q:"What does LED stand for?",options:["Light Emitting Diode","Long Emitting Device","Light Energy Detector","Luminous Emitting Device"],answer:0},
  {q:"What part of a cell contains genetic material?",options:["Mitochondria","Cell membrane","Nucleus","Ribosome"],answer:2},
  {q:"What is the measure of an object's resistance to changes in rotation?",options:["Torque","Inertia","Momentum","Friction"],answer:1},
  {q:"Which vitamin is produced when skin is exposed to sunlight?",options:["Vitamin A","Vitamin B","Vitamin C","Vitamin D"],answer:3},
  {q:"What is the most common programming language for web front-end?",options:["Python","Java","JavaScript","C++"],answer:2},
  {q:"What is the name for a substance that speeds up a chemical reaction without being consumed?",options:["Reagent","Catalyst","Inhibitor","Solvent"],answer:1},
  {q:"Which planet has the Great Red Spot?",options:["Mars","Saturn","Neptune","Jupiter"],answer:3},
  {q:"What is the unit of frequency?",options:["Watt","Joule","Hertz","Tesla"],answer:2},
  {q:"What is absolute zero in Celsius?",options:["−100°C","−173°C","−273°C","−373°C"],answer:2},
  {q:"Which element is a noble gas?",options:["Chlorine","Fluorine","Argon","Bromine"],answer:2},
  {q:"What is the chemical formula for carbon dioxide?",options:["CO","CO2","C2O","CD2"],answer:1},
  {q:"What part of a plant absorbs water from soil?",options:["Leaves","Stem","Roots","Flowers"],answer:2},
  {q:"What is the measurement of a star's brightness called?",options:["Luminosity","Magnitude","Intensity","Flux"],answer:1},
  {q:"What is the name of the force that opposes motion?",options:["Gravity","Tension","Friction","Normal"],answer:2},
  {q:"What does the Richter scale measure?",options:["Wind speed","Earthquake magnitude","Tornado intensity","Flood level"],answer:1},
  {q:"What type of bond shares electrons between atoms?",options:["Ionic","Metallic","Hydrogen","Covalent"],answer:3},
  {q:"What is the symbol for iron?",options:["Ir","Fr","Fe","Io"],answer:2},
  {q:"How many vertebrae does an adult human spine typically have?",options:["24","26","33","40"],answer:2},
  {q:"What is the name for the energy stored in chemical bonds?",options:["Kinetic energy","Potential energy","Chemical energy","Nuclear energy"],answer:2},
  {q:"What does HTML stand for?",options:["HyperText Markup Language","High-Text Markup Language","HyperText Machine Language","High Transfer Markup Language"],answer:0},
  {q:"Which blood cells fight infection?",options:["Red blood cells","Platelets","White blood cells","Plasma cells"],answer:2},
  {q:"What is the name of the scale used to measure acidity?",options:["Richter scale","pH scale","Kelvin scale","Mohs scale"],answer:1},
  {q:"What is the main component of the Sun?",options:["Oxygen","Carbon","Hydrogen","Helium"],answer:2},
  {q:"What is the name of the device that measures temperature?",options:["Barometer","Anemometer","Thermometer","Hygrometer"],answer:2},
  {q:"What is the smallest unit of matter?",options:["Cell","Molecule","Atom","Quark"],answer:2},
  {q:"What is the term for a change of state from solid to gas without passing through liquid?",options:["Condensation","Evaporation","Sublimation","Deposition"],answer:2},
  {q:"What does URL stand for?",options:["Uniform Resource Locator","Universal Resource Link","Unified Reference Locator","Universal Routing Link"],answer:0},
  {q:"What is the study of living organisms called?",options:["Chemistry","Physics","Biology","Geology"],answer:2},
  {q:"How many pairs of chromosomes do humans have?",options:["21","23","25","27"],answer:1},
  {q:"What is the process of a liquid becoming a gas called?",options:["Freezing","Condensation","Melting","Evaporation"],answer:3},
  {q:"Which organ is responsible for filtering blood?",options:["Liver","Kidneys","Spleen","Pancreas"],answer:1},
  {q:"What is the name of the force that acts between two charges?",options:["Gravity","Magnetic force","Electrostatic force","Nuclear force"],answer:2},
  {q:"What does GPS stand for?",options:["General Positioning System","Global Positioning System","Geographic Path System","Global Path Scanner"],answer:1},
  {q:"Which element has the atomic number 1?",options:["Helium","Lithium","Oxygen","Hydrogen"],answer:3},
  {q:"What is the name of the outer layer of the Earth?",options:["Mantle","Core","Crust","Asthenosphere"],answer:2},
  {q:"What is a group of stars forming a pattern called?",options:["Galaxy","Nebula","Constellation","Solar system"],answer:2},
  {q:"What does a barometer measure?",options:["Temperature","Wind speed","Atmospheric pressure","Humidity"],answer:2},
  {q:"Which part of the brain controls balance?",options:["Cerebrum","Cerebellum","Brain stem","Thalamus"],answer:1},
  {q:"What is the chemical symbol for nitrogen?",options:["Ni","Nt","Na","N"],answer:3},
  {q:"What are the two main gases in Earth's atmosphere?",options:["Oxygen and Carbon Dioxide","Nitrogen and Argon","Nitrogen and Oxygen","Oxygen and Hydrogen"],answer:2},
  {q:"What phenomenon causes the sky to appear blue?",options:["Reflection","Refraction","Rayleigh scattering","Diffraction"],answer:2},
  {q:"What is the name of the particle that carries no electric charge?",options:["Proton","Electron","Neutron","Positron"],answer:2},
  {q:"What type of rock is formed from cooled lava?",options:["Sedimentary","Metamorphic","Igneous","Composite"],answer:2},
  {q:"What does the CPU do in a computer?",options:["Store data","Display images","Execute instructions","Cool the system"],answer:1},
  {q:"What is the term for the amount of matter in an object?",options:["Volume","Density","Weight","Mass"],answer:3},
  {q:"Which layer of the Earth is the hottest?",options:["Crust","Mantle","Outer core","Inner core"],answer:3},
  {q:"What is the name of the process by which plants lose water?",options:["Photosynthesis","Respiration","Transpiration","Osmosis"],answer:2},
  {q:"What is the SI unit of energy?",options:["Watt","Newton","Joule","Pascal"],answer:2},
  {q:"What is the name of the galaxy we live in?",options:["Andromeda","Triangulum","Milky Way","Whirlpool"],answer:2},
  {q:"Which technology is used to store data using magnetic fields?",options:["SSD","RAM","HDD","ROM"],answer:2},
  {q:"What is the process of splitting an atomic nucleus?",options:["Fusion","Fission","Decay","Radiation"],answer:1},
  {q:"What organ in the human body produces bile?",options:["Pancreas","Kidney","Liver","Gallbladder"],answer:2},
  {q:"What is the formula for the area of a circle?",options:["2πr","πr²","πd","2πd"],answer:1},
  {q:"What type of electromagnetic radiation has the longest wavelength?",options:["Gamma rays","X-rays","Ultraviolet","Radio waves"],answer:3},
  {q:"What is the name for a substance that donates protons in a reaction?",options:["Base","Salt","Acid","Catalyst"],answer:2},
  {q:"What is the term for software that damages your computer?",options:["Firmware","Middleware","Malware","Hardware"],answer:2},
  {q:"What is the chemical formula for glucose?",options:["C6H12O6","C12H22O11","C6H6O6","C2H5OH"],answer:0},
  {q:"Which of these is NOT a type of cloud?",options:["Cumulus","Stratus","Nimbus","Radius"],answer:3},
  {q:"What is the name of the lens in the human eye?",options:["Cornea","Retina","Lens","Iris"],answer:2},
],

// ══════════════════════════════════════════════════════
// SET 3 — History & Geography (103 questions)
// ══════════════════════════════════════════════════════
[
  {q:"Who was the first person to walk on the Moon?",options:["Buzz Aldrin","Yuri Gagarin","Neil Armstrong","John Glenn"],answer:2},
  {q:"In what year did the Berlin Wall fall?",options:["1987","1988","1989","1990"],answer:2},
  {q:"Which ancient wonder was in Alexandria?",options:["Colossus","Hanging Gardens","Lighthouse","Statue of Zeus"],answer:2},
  {q:"Which empire was ruled by Julius Caesar?",options:["Greek","Ottoman","Roman","Byzantine"],answer:2},
  {q:"What language is most spoken worldwide (native speakers)?",options:["English","Hindi","Spanish","Mandarin Chinese"],answer:3},
  {q:"Which country invented paper?",options:["Egypt","India","China","Japan"],answer:2},
  {q:"Who was the first female Prime Minister of the UK?",options:["Queen Elizabeth II","Margaret Thatcher","Theresa May","Angela Merkel"],answer:1},
  {q:"In what year did Christopher Columbus reach the Americas?",options:["1488","1490","1492","1498"],answer:2},
  {q:"What mountain range separates Europe from Asia?",options:["Alps","Himalayas","Andes","Urals"],answer:3},
  {q:"What is the largest country by land area?",options:["China","Canada","USA","Russia"],answer:3},
  {q:"Which country hosted the 2016 Summer Olympics?",options:["China","UK","Brazil","Russia"],answer:2},
  {q:"Which river runs through Egypt?",options:["Amazon","Congo","Mississippi","Nile"],answer:3},
  {q:"What year did World War I begin?",options:["1912","1914","1916","1918"],answer:1},
  {q:"Which country was Napoleon Bonaparte from?",options:["France born in Corsica","Italy","Spain","Britain"],answer:0},
  {q:"What was the first country to give women the right to vote?",options:["USA","UK","New Zealand","Australia"],answer:2},
  {q:"Which civilization built Machu Picchu?",options:["Aztec","Maya","Inca","Olmec"],answer:2},
  {q:"In what year did the Titanic sink?",options:["1910","1912","1914","1916"],answer:1},
  {q:"Who was the first President of the United States?",options:["John Adams","Thomas Jefferson","George Washington","James Madison"],answer:2},
  {q:"What ancient structure was built around 2560 BC in Egypt?",options:["Colosseum","Parthenon","Great Pyramid","Stonehenge"],answer:2},
  {q:"Which country has the most time zones?",options:["USA","Russia","China","France"],answer:3},
  {q:"What was the name of the ship that brought the Pilgrims to America?",options:["Santa María","Mayflower","Beagle","Endeavour"],answer:1},
  {q:"Which country is home to the Amazon Rainforest (mostly)?",options:["Colombia","Peru","Venezuela","Brazil"],answer:3},
  {q:"Who wrote the Declaration of Independence?",options:["George Washington","Benjamin Franklin","John Adams","Thomas Jefferson"],answer:3},
  {q:"Which war was fought between the North and South of the USA?",options:["Revolutionary War","War of 1812","Civil War","Mexican-American War"],answer:2},
  {q:"What city is the capital of Turkey?",options:["Istanbul","Izmir","Bursa","Ankara"],answer:3},
  {q:"Which empire was the largest in history by land area?",options:["Roman Empire","Mongol Empire","British Empire","Ottoman Empire"],answer:2},
  {q:"What year did the first man-made satellite launch?",options:["1955","1957","1959","1961"],answer:1},
  {q:"Which country was the first to land a rover on Mars?",options:["Russia","China","USA","European Union"],answer:2},
  {q:"What is the capital of South Africa?",options:["Cape Town only","Johannesburg","Pretoria (executive)","Durban"],answer:2},
  {q:"Who was the longest-reigning British monarch?",options:["George III","Victoria","Elizabeth II","Henry VIII"],answer:2},
  {q:"On which continent is the Sahara Desert located?",options:["Asia","Middle East","Africa","South America"],answer:2},
  {q:"What year did India gain independence from Britain?",options:["1945","1947","1949","1951"],answer:1},
  {q:"Which civilisation first developed writing?",options:["Egyptian","Chinese","Greek","Sumerian"],answer:3},
  {q:"What is the capital of Nigeria?",options:["Lagos","Kano","Ibadan","Abuja"],answer:3},
  {q:"The Great Wall of China was primarily built to protect against which group?",options:["Persians","Romans","Mongols","Japanese"],answer:2},
  {q:"What year did the French Revolution begin?",options:["1779","1783","1789","1795"],answer:2},
  {q:"Which country has the longest coastline?",options:["Russia","Norway","Australia","Canada"],answer:3},
  {q:"What was the name of the first artificial satellite?",options:["Explorer 1","Apollo 1","Sputnik 1","Vostok 1"],answer:2},
  {q:"Which city was the capital of the Byzantine Empire?",options:["Rome","Athens","Jerusalem","Constantinople"],answer:3},
  {q:"What country was Adolf Hitler born in?",options:["Germany","Switzerland","Austria","Hungary"],answer:2},
  {q:"Which mountain range contains Mount Everest?",options:["Andes","Alps","Rockies","Himalayas"],answer:3},
  {q:"What is the capital of Kenya?",options:["Mombasa","Kisumu","Nakuru","Nairobi"],answer:3},
  {q:"Who painted the Sistine Chapel ceiling?",options:["Leonardo da Vinci","Raphael","Michelangelo","Botticelli"],answer:2},
  {q:"Which country has the most UNESCO World Heritage Sites?",options:["France","China","Spain","Italy"],answer:3},
  {q:"What year did the Soviet Union collapse?",options:["1989","1990","1991","1992"],answer:2},
  {q:"What ocean lies between Europe and the Americas?",options:["Pacific","Indian","Arctic","Atlantic"],answer:3},
  {q:"What was the first country to circumnavigate the globe?",options:["Portugal","Spain","Britain","Netherlands"],answer:1},
  {q:"Which US state was the last to join the union?",options:["Alaska","Hawaii","New Mexico","Arizona"],answer:1},
  {q:"What is the capital of Pakistan?",options:["Lahore","Karachi","Peshawar","Islamabad"],answer:3},
  {q:"Who led the Cuban Revolution?",options:["Che Guevara","Raúl Castro","Fulgencio Batista","Fidel Castro"],answer:3},
  {q:"Which country gifted the Statue of Liberty to the USA?",options:["Britain","Germany","Italy","France"],answer:3},
  {q:"What year did humans first reach the Moon?",options:["1965","1967","1969","1971"],answer:2},
  {q:"Which river runs through London?",options:["Avon","Severn","Thames","Trent"],answer:2},
  {q:"What ancient trade route connected China to Europe?",options:["Amber Road","Spice Route","Silk Road","Salt Road"],answer:2},
  {q:"Which country has the highest population in Africa?",options:["Egypt","Ethiopia","DRC","Nigeria"],answer:3},
  {q:"Who was the last pharaoh of ancient Egypt?",options:["Nefertiti","Cleopatra","Hatshepsut","Nefertari"],answer:1},
  {q:"What is the smallest country in Africa?",options:["Gambia","Djibouti","Comoros","Seychelles"],answer:3},
  {q:"In which modern country did the ancient city of Babylon exist?",options:["Iran","Syria","Jordan","Iraq"],answer:3},
  {q:"What is the capital of Morocco?",options:["Casablanca","Fes","Marrakech","Rabat"],answer:3},
  {q:"Who was the first woman to win a Nobel Prize?",options:["Dorothy Hodgkin","Rosalind Franklin","Marie Curie","Lise Meitner"],answer:2},
  {q:"Which country built the Panama Canal?",options:["Colombia","France then USA","Spain","Britain"],answer:1},
  {q:"What is the capital of Vietnam?",options:["Ho Chi Minh City","Da Nang","Hue","Hanoi"],answer:3},
  {q:"The Battle of Waterloo took place in which modern country?",options:["France","Netherlands","Germany","Belgium"],answer:3},
  {q:"What year did the Second World War begin?",options:["1937","1938","1939","1940"],answer:2},
  {q:"Which country is known as the Land of the Rising Sun?",options:["China","Korea","Vietnam","Japan"],answer:3},
  {q:"What is the capital of Ethiopia?",options:["Addis Ababa","Nairobi","Khartoum","Djibouti"],answer:0},
  {q:"Who wrote 'The Art of War'?",options:["Confucius","Lao Tzu","Sun Tzu","Mencius"],answer:2},
  {q:"Which continent has the most countries?",options:["Asia","Americas","Europe","Africa"],answer:3},
  {q:"What is the capital of Saudi Arabia?",options:["Mecca","Medina","Jeddah","Riyadh"],answer:3},
  {q:"Which explorer first reached India by sea from Europe?",options:["Christopher Columbus","Ferdinand Magellan","Vasco da Gama","Amerigo Vespucci"],answer:2},
  {q:"What is the tallest building in the world (as of 2024)?",options:["Shanghai Tower","One World Trade Center","Burj Khalifa","Makkah Clock Tower"],answer:2},
  {q:"Which country has the largest oil reserves?",options:["Saudi Arabia","Iran","Iraq","Venezuela"],answer:3},
  {q:"What is the capital of Indonesia?",options:["Surabaya","Bandung","Medan","Jakarta"],answer:3},
  {q:"Who founded the Mongol Empire?",options:["Kublai Khan","Timur","Genghis Khan","Batu Khan"],answer:2},
  {q:"What is the official language of Brazil?",options:["Spanish","French","English","Portuguese"],answer:3},
  {q:"In which city is the Colosseum located?",options:["Athens","Cairo","Rome","Istanbul"],answer:2},
  {q:"What does the Great Barrier Reef run along?",options:["New Zealand","Indonesia","Papua New Guinea","Australia"],answer:3},
  {q:"Which US state is known as the Sunshine State?",options:["California","Texas","Hawaii","Florida"],answer:3},
  {q:"What is the capital of Sweden?",options:["Oslo","Copenhagen","Helsinki","Stockholm"],answer:3},
  {q:"Who was the leader of the Soviet Union during World War II?",options:["Lenin","Khrushchev","Stalin","Brezhnev"],answer:2},
  {q:"What is the capital of the Philippines?",options:["Cebu","Davao","Quezon City","Manila"],answer:3},
  {q:"Which country has the largest economy in Africa?",options:["Egypt","South Africa","Ethiopia","Nigeria"],answer:3},
  {q:"Who invented the printing press?",options:["Leonardo da Vinci","Johannes Gutenberg","Isaac Newton","Galileo Galilei"],answer:1},
  {q:"What is the largest lake in Africa?",options:["Lake Malawi","Lake Tanganyika","Lake Chad","Lake Victoria"],answer:3},
  {q:"Which country is home to the Taj Mahal?",options:["Pakistan","Bangladesh","Nepal","India"],answer:3},
  {q:"What year did the USA declare independence?",options:["1774","1775","1776","1777"],answer:2},
  {q:"What is the capital of Peru?",options:["Cusco","Arequipa","Trujillo","Lima"],answer:3},
  {q:"Which country was the first to use paper money?",options:["India","Egypt","Greece","China"],answer:3},
  {q:"What is the national sport of Japan?",options:["Judo","Karate","Sumo","Baseball"],answer:2},
  {q:"Who was the first woman to fly solo across the Atlantic?",options:["Harriet Quimby","Jacqueline Cochran","Amelia Earhart","Bessie Coleman"],answer:2},
  {q:"What is the capital of New Zealand?",options:["Auckland","Christchurch","Dunedin","Wellington"],answer:3},
  {q:"Which country has won the most FIFA World Cups?",options:["Germany","Italy","Argentina","Brazil"],answer:3},
  {q:"What is the longest wall in the world?",options:["Hadrian's Wall","Berlin Wall","Great Wall of China","Western Wall"],answer:2},
  {q:"What is the capital of Colombia?",options:["Medellín","Cali","Cartagena","Bogotá"],answer:3},
  {q:"Which US state has the most national parks?",options:["Wyoming","Utah","Colorado","California"],answer:3},
  {q:"In what year was the United Nations founded?",options:["1943","1944","1945","1946"],answer:2},
  {q:"What was the currency of Germany before the Euro?",options:["Franc","Mark","Schilling","Lira"],answer:1},
],

// ══════════════════════════════════════════════════════
// SET 4 — Pop Culture, Sport & Entertainment (101 questions)
// ══════════════════════════════════════════════════════
[
  {q:"How many players are on a basketball team on the court?",options:["4","5","6","7"],answer:1},
  {q:"Which band sang 'Bohemian Rhapsody'?",options:["The Beatles","Led Zeppelin","Queen","Pink Floyd"],answer:2},
  {q:"What sport is played at Wimbledon?",options:["Badminton","Squash","Tennis","Table Tennis"],answer:2},
  {q:"How many rings are on the Olympic flag?",options:["4","5","6","7"],answer:1},
  {q:"In chess, which piece can only move diagonally?",options:["Rook","Knight","Bishop","Queen"],answer:2},
  {q:"Who directed 'Jurassic Park' (1993)?",options:["James Cameron","George Lucas","Steven Spielberg","Ridley Scott"],answer:2},
  {q:"What is the name of Batman's butler?",options:["James","Alfred","Thomas","Arthur"],answer:1},
  {q:"How many Grammy Awards did Michael Jackson win in total?",options:["10","13","15","17"],answer:1},
  {q:"What is the best-selling video game of all time?",options:["Tetris","GTA V","Minecraft","Mario Bros"],answer:2},
  {q:"In what year was the first iPhone released?",options:["2005","2006","2007","2008"],answer:2},
  {q:"What is the highest possible score in a single bowling game?",options:["10","200","300","400"],answer:2},
  {q:"Who plays Iron Man in the Marvel Cinematic Universe?",options:["Chris Evans","Chris Hemsworth","Robert Downey Jr.","Mark Ruffalo"],answer:2},
  {q:"Which country invented football (soccer)?",options:["Brazil","Spain","France","England"],answer:3},
  {q:"What is the name of the lion in 'The Lion King'?",options:["Mufasa","Scar","Rafiki","Simba"],answer:3},
  {q:"How many players are in a football (soccer) team?",options:["9","10","11","12"],answer:2},
  {q:"Which TV show features the character Walter White?",options:["Dexter","Better Call Saul","Breaking Bad","Ozark"],answer:2},
  {q:"What is the fastest production car in the world (approx.)?",options:["Bugatti Chiron Super Sport","Koenigsegg Jesko Absolut","SSC Tuatara","Hennessey Venom F5"],answer:1},
  {q:"Who wrote the Harry Potter series?",options:["Suzanne Collins","Stephenie Meyer","J.R.R. Tolkien","J.K. Rowling"],answer:3},
  {q:"How many time zones does the USA span?",options:["4","5","6","7"],answer:2},
  {q:"What is the most streamed song on Spotify of all time (as of 2024)?",options:["Shape of You","Blinding Lights","Dance Monkey","Despacito"],answer:1},
  {q:"Which sport uses a shuttlecock?",options:["Tennis","Squash","Badminton","Racquetball"],answer:2},
  {q:"What is the name of the Marvel superhero who wields a hammer?",options:["Captain America","Iron Man","Black Panther","Thor"],answer:3},
  {q:"How many episodes are in the first season of 'Friends'?",options:["20","22","24","26"],answer:2},
  {q:"Which country has the most Oscar wins for Best Foreign Language Film?",options:["France","Italy","Spain","Japan"],answer:1},
  {q:"What is the name of Harry Potter's owl?",options:["Crookshanks","Scabbers","Fang","Hedwig"],answer:3},
  {q:"How long is a marathon (km)?",options:["39.2","40.2","41.2","42.2"],answer:3},
  {q:"What is the most watched Super Bowl halftime show ever?",options:["Beyoncé 2013","Bruno Mars 2014","Katy Perry 2015","Lady Gaga 2017"],answer:2},
  {q:"Which actor played Jack Dawson in Titanic?",options:["Brad Pitt","Johnny Depp","Leonardo DiCaprio","Matt Damon"],answer:2},
  {q:"What is the name of the pub in 'Cheers'?",options:["McLaren's","Paddy's Pub","The Cheers Bar","The Bull & Finch"],answer:2},
  {q:"Which team has won the most NBA championships?",options:["Los Angeles Lakers","Chicago Bulls","Golden State Warriors","Boston Celtics"],answer:3},
  {q:"What video game franchise features characters like Link and Zelda?",options:["Final Fantasy","Fire Emblem","The Legend of Zelda","Kingdom Hearts"],answer:2},
  {q:"Who sang 'Thriller'?",options:["Prince","Stevie Wonder","Michael Jackson","James Brown"],answer:2},
  {q:"What sport does Serena Williams play?",options:["Badminton","Squash","Table Tennis","Tennis"],answer:3},
  {q:"What is the name of the fictional country in 'Black Panther'?",options:["Kahndaq","Madripoor","Genosha","Wakanda"],answer:3},
  {q:"Which streaming service produced 'Stranger Things'?",options:["HBO","Amazon Prime","Disney+","Netflix"],answer:3},
  {q:"How many colours are in the Olympic rings?",options:["4","5","6","7"],answer:1},
  {q:"What is the name of Spider-Man's alter ego?",options:["Bruce Banner","Peter Parker","Clark Kent","Tony Stark"],answer:1},
  {q:"Which country has the most World Cup wins in women's soccer?",options:["Germany","Brazil","Sweden","USA"],answer:3},
  {q:"What is the name of the spaceship in 'Star Wars' flown by Han Solo?",options:["X-Wing","TIE Fighter","Imperial Shuttle","Millennium Falcon"],answer:3},
  {q:"Which rock band has sold the most albums worldwide?",options:["Led Zeppelin","The Beatles","The Rolling Stones","Pink Floyd"],answer:1},
  {q:"What is the name of the Hogwarts ghost known as the 'Bloody Baron'?",options:["Nearly Headless Nick","The Grey Lady","The Fat Friar","The Bloody Baron"],answer:3},
  {q:"Who is the highest-paid actor in Hollywood history?",options:["Dwayne Johnson","Tom Cruise","Leonardo DiCaprio","Will Smith"],answer:0},
  {q:"Which country has the most Formula 1 World Championships?",options:["Germany","Brazil","UK","USA"],answer:1},
  {q:"What year did Facebook launch publicly?",options:["2002","2003","2004","2005"],answer:2},
  {q:"Which musician has the most Grammy nominations ever?",options:["Jay-Z","Beyoncé","Quincy Jones","Georg Solti"],answer:1},
  {q:"What is the name of the animated fish in 'Finding Nemo'?",options:["Dory","Marlin","Gill","Nemo"],answer:3},
  {q:"Which country hosts the Tour de France?",options:["Belgium","Italy","France","Spain"],answer:2},
  {q:"Who voiced Woody in 'Toy Story'?",options:["Tom Hanks","Tom Cruise","Brad Pitt","Eddie Murphy"],answer:0},
  {q:"How many points is a touchdown worth in American football?",options:["3","5","6","7"],answer:2},
  {q:"Which movie features the quote 'You can't handle the truth'?",options:["The Godfather","A Few Good Men","Good Will Hunting","Rain Man"],answer:1},
  {q:"What does the 'G' stand for in GOAT (sports term)?",options:["Grandest","Gold","Greatest","Gifted"],answer:2},
  {q:"Which video game character is known for collecting coins and jumping on mushrooms?",options:["Link","Mega Man","Kirby","Mario"],answer:3},
  {q:"What is the name of the coffee shop in 'Friends'?",options:["Starbucks","The Perk","Central Perk","Java Jitters"],answer:2},
  {q:"How many Grand Slam tennis titles did Roger Federer win?",options:["17","18","19","20"],answer:3},
  {q:"What is the name of the villain in 'The Lion King'?",options:["Scar","Mufasa","Hyena","Zazu"],answer:0},
  {q:"Which country hosted the 2022 FIFA World Cup?",options:["Russia","UAE","Saudi Arabia","Qatar"],answer:3},
  {q:"How many seasons does 'Game of Thrones' have?",options:["6","7","8","9"],answer:2},
  {q:"What is the name of the main character in 'The Witcher' series?",options:["Geralt","Jaskier","Ciri","Yennefer"],answer:0},
  {q:"Which band sang 'Hotel California'?",options:["The Rolling Stones","Led Zeppelin","Eagles","Fleetwood Mac"],answer:2},
  {q:"What is the most downloaded app of all time?",options:["Facebook","Instagram","WhatsApp","TikTok"],answer:0},
  {q:"Who is the all-time leading scorer in NBA history?",options:["Michael Jordan","Kobe Bryant","LeBron James","Kareem Abdul-Jabbar"],answer:2},
  {q:"What is the name of the island in 'Lost'?",options:["Crab Key","The Island (no name)","Hydra Island","Mystery Island"],answer:1},
  {q:"Which animated series features the characters Homer, Bart and Marge?",options:["Family Guy","Futurama","American Dad","The Simpsons"],answer:3},
  {q:"What is the name of James Bond's boss?",options:["N","M","Q","R"],answer:1},
  {q:"Which chess piece can jump over other pieces?",options:["Bishop","Rook","Queen","Knight"],answer:3},
  {q:"How many points is a free throw worth in basketball?",options:["1","2","3","4"],answer:0},
  {q:"What is the real name of rapper Eminem?",options:["Marshall Mathers","Michael Matthews","Marcus Mills","Miles Morton"],answer:0},
  {q:"Which actor has won the most Academy Awards for acting?",options:["Jack Nicholson","Meryl Streep","Katharine Hepburn","Daniel Day-Lewis"],answer:2},
  {q:"What year did the first Harry Potter movie release?",options:["1999","2000","2001","2002"],answer:2},
  {q:"Which sport uses the term 'birdie'?",options:["Tennis","Badminton","Golf","Cricket"],answer:2},
  {q:"What is the name of the Avengers HQ in the MCU?",options:["Stark Tower","Xavier's Mansion","The Compound","S.H.I.E.L.D. HQ"],answer:2},
  {q:"Which country produced the TV show 'Dark'?",options:["UK","Sweden","USA","Germany"],answer:3},
  {q:"Who is the author of 'A Song of Ice and Fire' (Game of Thrones)?",options:["J.R.R. Tolkien","Robert Jordan","George R.R. Martin","Brandon Sanderson"],answer:2},
  {q:"Which sport has terms 'love', 'deuce' and 'fault'?",options:["Badminton","Squash","Tennis","Table tennis"],answer:2},
  {q:"Who sang 'Shape of You'?",options:["Sam Smith","Justin Bieber","Harry Styles","Ed Sheeran"],answer:3},
  {q:"What is the highest-grossing movie of all time?",options:["Avengers: Endgame","Titanic","Avatar","Star Wars: The Force Awakens"],answer:2},
  {q:"Which country is home to the video game company Nintendo?",options:["South Korea","China","USA","Japan"],answer:3},
  {q:"What is the name of the fictional school in Harry Potter?",options:["Durmstrang","Beauxbatons","Castelobruxo","Hogwarts"],answer:3},
  {q:"How many players are on a volleyball team on the court?",options:["5","6","7","8"],answer:1},
  {q:"Which superhero is known as 'the Caped Crusader'?",options:["Superman","Spider-Man","Batman","Captain America"],answer:2},
  {q:"What is the name of Sherlock Holmes's address?",options:["221A Baker Street","221B Baker Street","221C Baker Street","221 Baker Street"],answer:1},
  {q:"Who composed the 'Four Seasons'?",options:["Bach","Mozart","Beethoven","Vivaldi"],answer:3},
  {q:"Which sport features a 'slam dunk'?",options:["Volleyball","Basketball","Handball","Water polo"],answer:1},
  {q:"What is the name of the fictional land in 'The Lion, the Witch and the Wardrobe'?",options:["Middle-earth","Westeros","Narnia","Neverland"],answer:2},
  {q:"What is the official language of the USA?",options:["English (official)","English (de facto, no official language)","American English","English and Spanish"],answer:1},
  {q:"Which DJ is known as 'The God of DJs'?",options:["Tiësto","Deadmau5","Calvin Harris","DJ Khaled"],answer:0},
  {q:"In what decade was the Super Bowl first played?",options:["1950s","1960s","1970s","1980s"],answer:1},
  {q:"What is the name of the actor who plays Captain Jack Sparrow?",options:["Orlando Bloom","Keira Knightley","Geoffrey Rush","Johnny Depp"],answer:3},
  {q:"Which music video was the first to reach 1 billion views on YouTube?",options:["Gangnam Style","Baby","Waka Waka","Bad Romance"],answer:0},
  {q:"How many cards are dealt to each player in poker (Texas Hold'em)?",options:["1","2","3","4"],answer:1},
  {q:"Who holds the record for the most Olympic gold medals?",options:["Usain Bolt","Simone Biles","Michael Phelps","Carl Lewis"],answer:2},
  {q:"What is the name of the lead character in 'The Hunger Games'?",options:["Tris Prior","Hermione Granger","Katniss Everdeen","Bella Swan"],answer:2},
  {q:"Which country has won the most cricket World Cup titles?",options:["England","India","Pakistan","Australia"],answer:3},
  {q:"What is the name of the restaurant in 'The Bear' TV show?",options:["The Beef","The Grill","The Kitchen","The Chop"],answer:0},
  {q:"How many holes are on a standard golf course?",options:["9","12","18","21"],answer:2},
],

];

// ── loadQuestions(n) ─────────────────────────────────────────
// Picks a random set and returns n shuffled questions.
// If n > set size, wraps around using multiple shuffles.
function loadQuestions(n) {
  n = n || 12;
  const setIdx  = Math.floor(Math.random() * QUESTION_SETS.length);
  const srcPool = QUESTION_SETS[setIdx];

  // Build a pool large enough for n questions without duplicating unless necessary
  let pool = [];
  while (pool.length < n) {
    pool = pool.concat(shufflePool([...srcPool]));
  }
  return pool.slice(0, n);
}

function shufflePool(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
